In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [13]:
one_hot('amazing restaurant',30)

[23, 17]

In [20]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[26, 28], [23, 17], [10, 29], [16, 7, 20], [12, 26, 3], [4, 28], [24, 26, 6], [20, 21], [20, 26], [6, 7]]


In [24]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[26 28  0  0]
 [23 17  0  0]
 [10 29  0  0]
 [16  7 20  0]
 [12 26  3  0]
 [ 4 28  0  0]
 [24 26  6  0]
 [20 21  0  0]
 [20 26  0  0]
 [ 6  7  0  0]]


In [29]:
embeded_vector_size=5
model = Sequential()
model.add(Embedding(vocab_size,embeded_vector_size,input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [30]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 20)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
x=padded_reviews
y=sentiment
model.fit(x,y,epochs=50,verbose=0)

In [37]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30